Feat/django
BharatSahAIyak/autotune pull request #32
Opened 2024-04-20 20:50 UTC by sooraj1002

2024-04-23 04:13 UTC, KDwevedi reviewed
Minor cleanups and requests for extracting out contextual information from code comments to repo issues.

Otherwise LGTM

2024-04-23 04:13 UTC, KDwevedi commented on workflow/task.py
> +                # self.generate_or_refine(
Why do we have this section commented out?

2024-04-23 04:13 UTC, KDwevedi commented on workflow/views.py
> +# what is task table
If these comments are relevant, let's create a ticket out of them
If not, let's remove them

2024-04-23 04:13 UTC, KDwevedi commented on workflow/views.py
> +    # TBD
Can we create a ticket out of this?
Why is it TBD?

2024-04-23 05:21 UTC, sooraj1002 commented on workflow/views.py
> +    # TBD
This is the final step after generating the samples. We had decided to work on this once the first part is completed

2024-04-23 05:46 UTC, sooraj1002 commented on workflow/views.py
> +    # TBD
https://github.com/BharatSahAIyak/autotune/issues/33

2024-04-23 05:49 UTC, sooraj1002 commented on workflow/views.py
> +# what is task table
removed https://github.com/BharatSahAIyak/autotune/commit/8553a17a998c9768bbe87d3c39f3ceeb2c363a53

2024-04-24 04:07 UTC, KDwevedi requested changes
- [ ] Note what expected functionality of Autotune is limited by #33
  - [ ] Add a desc of this limited functionality to the [pr comment](https://github.com/BharatSahAIyak/autotune/pull/32#issue-2254715351) 
- [ ] [Make the service ready for deployment](https://github.com/BharatSahAIyak/docker-bhasai/blob/dev/docs/onboarding.md)

2024-04-24 07:28 UTC, merged